from . import hr_hospital_person
from . import hr_hospital_patient
from . import hr_hospital_doctor
from . import hr_hospital_doctor_schedule
from . import hr_hospital_disease
from . import hr_hospital_diagnosis
from . import hr_hospital_disease_type
from . import hr_hospital_appointment
from . import hr_hospital_contact_person
from . import hr_hospital_personal_doctor_history
from . import hr_hospital_research
from . import hr_hospital_research_type
from . import hr_hospital_sample
